### PR TITLE
 Code for achieving max brightness during webcam

### LINKED ISSUE #19: Increase the brightness of the screen while using web cam
In low light condition, the webcam can't recognize faces.
Make a funtuon that 
* reads the current brightness and stores it.
* changes screen brightness to 100%.
* restores original brightness

### PR DESCRIPTION
**Pull request by AdirthaBorgohain**
This is just the basic code. Needs a lot of optimizations. At the moment, we need to enter the sudo password to just maximize the brightness. See if you can come up with any solution to remove the need for sudo password input. Resolves #19

### CODE REVIEW

**Comment by sourishsarmah** [comment]
using "sudo" for increasing brightness will not be efficient.
try to use the method used by gnome to increase the brightness - 
``` [Using DBus with Gnome](https://wiki.archlinux.org/index.php/Backlight#Using_DBus_with_Gnome) ```

**Comment by AdirthaBorgohain** [comment]
> using "sudo" for increasing brightness will not be efficient.
> try to use the method used by gnome to increase the brightness -
> [Using DBus with Gnome](https://wiki.archlinux.org/index.php/Backlight#Using_DBus_with_Gnome)

Working on it.

**Comment by AdirthaBorgohain** [comment]
I have made all the changes needed. The script should be working as desired now. Review and merge after testing if there are no bugs. 
However, since we are using DBus now, gods_eye will only work on gnome environments.

**Comment by sourishsarmah** [comment]
This is working fine on gnome.

**Pull request merged**
